default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: basic_rails_app_dev

test:
  <<: *default
  database: basic_rails_app_test

production:
  <<: *default
  database: basic_rails_app_dev
